### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by MonadicT** [lamdu/hypertypes#11]
I was playing around with the release on stackage and running into missing modules problem (Hyper.Syntax.App and others) which was me looking at the HEAD version and using version 0.1.0.2 release. Unfortunately, there are no release tags which makes it difficult to browse the code for the release. It would be very helpful if you could tag the repo when you release new versions.

Thank you! Looking forward to using hypertypes.

**Comment by yairchu** [comment]
Good suggestion. Tags for released versions [are now available](https://github.com/lamdu/hypertypes/tags) and I'll tag future releases as well.
