### ISSUE TITLE
Is it possible to get the latest version uploaded to Hackage please

### ISSUE THREAD

**Issue by expipiplus1** [lamdu/hypertypes#17]
The version on there is ~2 years old by now :)

On a similar note, and I don't mean this to sound flippant, but how would you feel about splitting up the package into some smaller pieces. At the moment it's very easy to look at it and see hypertypes as an ecosystem to buy into, but the "core" could be very neatly separated from the AST/Infer/Unify side of things, and would perhaps be an easier pick for those looking for "recursion schemes, but for mutually recursive datatypes".

This is,of course not a project I've contributed to yet and there are benefits to having a monoproject!

**Comment by yairchu** [comment]
Done :)

> how would you feel about splitting up the package into some smaller pieces. At the moment it's very easy to look at it and see hypertypes as an ecosystem to buy into, but the "core" could be very neatly separated from the AST/Infer/Unify side of things, and would perhaps be an easier pick for those looking for "recursion schemes, but for mutually recursive datatypes".

Sounds good. Will you open that as a separate issue?

> This is,of course not a project I've contributed to yet and there are benefits to having a monoproject!

I think that it can still be a monorepo with several packages in it and it wouldn't lose any benefits.

**Comment by expipiplus1** [comment]
Thanks!
